name: Run Java Programs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java files
      run: |
        mkdir -p bin
        javac -d bin $(find . -name "*.java")

    - name: List classes with main method
      run: |
        echo "Classes with main method:"
        grep -lr 'public static void main' . | grep .java

    - name: Run Main class (if exists)
      run: |
        if [ -f ./bin/Main.class ]; then
          java -cp bin Main
        else
          echo "⚠️ Main.class not found. Please check your entry point."
        fi
      continue-on-error: true
