name: Run Java Programs

on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create bin directory
        run: mkdir -p bin

      - name: Compile all Java files
        run: |
          find . -name "*.java" > sources.txt
          javac -d bin @sources.txt

      - name: Run all Java classes with main method
        run: |
          for file in $(find . -name "*.java"); do
            className=$(basename "$file" .java)
            if grep -q "public static void main" "$file"; then
              echo "Running: $className"
              java -cp bin "$className" < /dev/null || echo "⚠️ Error running $className"
            fi
          done
